attendance/api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from .views import MemberList, MemberDetail

urlpatterns = [
    path('member/', MemberList.as_view()),
    path('member/<int:pk>/', MemberDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

attendance/attendance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include(('api.urls','api'))),
    path('', include(('webui.urls', 'webui'))),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

attendance/webui/urls.py
from django.urls import path
from .views import LandingPage, MemberListView, index, CreateTransaction

urlpatterns = [
    path('', LandingPage.as_view(), name="home"),
    path('sewadaar-list', MemberListView.as_view()),
    path('create-transaction', CreateTransaction.as_view()),
]

attendance/webui/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.core.validators import RegexValidator

# Create your models here.

GENDER_TYPE = (
    ('M', 'Male'),
    ('F', 'Female'),
)

ACTIVE_TYPE = (
    ('ACT', 'Active'), # Green State
    ('TRAN', 'Transit'), # Orange State
    ('INACT', 'InActive'), # Orange State
)

class MemberType(models.Model):
    """Model definition for MemberType.
    Using this as to identify Sewadar, IC, and Admin"""

    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)

    class Meta:
        """Meta definition for MemberType."""

        verbose_name = 'MemberType'
        verbose_name_plural = 'MemberTypes'

    def __str__(self):
        """Unicode representation of MemberType."""
        return self.name

    # def save(self):
    #     """Save method for MemberType."""
    #     pass

    # def get_absolute_url(self):
    #     """Return absolute url for MemberType."""
    #     return ('')

    # TODO: Define custom methods here

class Center(models.Model):
    """Model definition for Center."""

    name = models.CharField(max_length=50)

    class Meta:
        """Meta definition for Center."""

        verbose_name = 'Center'
        verbose_name_plural = 'Centers'

    def __str__(self):
        """Unicode representation of Center."""
        return '{}'.format(self.name ) # TODO

    # def save(self):
    #     """Save method for Center."""
    #     pass

    # def get_absolute_url(self):
    #     """Return absolute url for Center."""
    #     return ('')

    # TODO: Define custom methods here

class Member(models.Model):
    """Model definition for Member."""

    # ID and FK
    MemberTypeDetails = models.ForeignKey('webui.MemberType', on_delete=models.DO_NOTHING)
    CenterDetails = models.ForeignKey('webui.Center', on_delete=models.DO_NOTHING)
    id = models.BigIntegerField(unique=True,primary_key=True)

    name = models.CharField(max_length=50)
    father_name = models.CharField(max_length=50,blank=True)
    # Can make a relation
    gender = models.CharField(choices=GENDER_TYPE,default='M', max_length=10)

    phone_regex = RegexValidator(regex=r'^\+?1?\d{12}$', message="Phone number must be entered in the format: '+91'. Up to 10 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=15, blank=True) # validators should be a list
    phone_number_alt = models.CharField(max_length=10, blank=True) # validators should be a list

    department = models.CharField(max_length=50, default="Security")

    class Meta:
        """Meta definition for Member."""

        verbose_name = 'Member'
        verbose_name_plural = 'Members'

    def __str__(self):
        """Unicode representation of Member."""
        return '{}'.format(self.name ) # TODO

    # def save(self):
    #     """Save method for Member."""
    #     pass

    # def get_absolute_url(self):
    #     """Return absolute url for Member."""
    #     return ('')

    # TODO: Define custom methods here

class SecurityPost(models.Model):
    """Model definition for SecurityPost."""

    name = models.CharField(max_length=50)

    class Meta:
        """Meta definition for SecurityPost."""

        verbose_name = 'SecurityPost'
        verbose_name_plural = 'SecurityPosts'

    def __str__(self):
        """Unicode representation of SecurityPost."""
        return '{}'.format(self.name ) # TODO

    # def save(self):
    #     """Save method for SecurityPost."""
    #     pass

    # def get_absolute_url(self):
    #     """Return absolute url for SecurityPost."""
    #     return ('')

    # TODO: Define custom methods here

class Transaction(models.Model):
    """Model definition for Transaction."""

    MemberDetails = models.ForeignKey('webui.Member', on_delete=models.DO_NOTHING)
    SecurityPostDetails = models.ForeignKey('webui.SecurityPost', on_delete=models.DO_NOTHING)

    inTime = models.DateTimeField(auto_now=False)
    outtime = models.DateTimeField(auto_now=False)
    status = models.CharField(choices=ACTIVE_TYPE, max_length=50, default='ACT')
    altcontact = PhoneNumberField(blank=True)
    misc = models.TextField(blank=True)

    class Meta:
        """Meta definition for Transaction."""

        verbose_name = 'Transaction'
        verbose_name_plural = 'Transactions'

    def __str__(self):
        """Unicode representation of Transaction."""
        return '{}'.format(self.inTime ) # TODO

    # def save(self):
    #     """Save method for Transaction."""
    #     pass

    # def get_absolute_url(self):
    #     """Return absolute url for Transaction."""
    #     return ('')

    # TODO: Define custom methods here

# OPen Transdaction 

class MemberTemporary(models.Model):
    """Model definition for MemberTemporary."""

    # ID and FK
    CenterDetails = models.ForeignKey('webui.Center', on_delete=models.DO_NOTHING)

    MemberTypeDetails = models.CharField(default='Sewadaar', max_length=50)
    name = models.CharField(max_length=50)
    father_name = models.CharField(max_length=50,blank=True)
    # Can make a relation
    gender = models.CharField(choices=GENDER_TYPE,default='M', max_length=10)
    contact = PhoneNumberField()
    altcontact = PhoneNumberField(blank=True)
    department = models.CharField(max_length=50, default="Security")

    class Meta:
        """Meta definition for MemberTemporary."""

        verbose_name = 'MemberTemporary'
        verbose_name_plural = 'MemberTemporarys'

    def __str__(self):
        """Unicode representation of MemberTemporary."""
        return '{}'.format(self.name ) # TODO

    # def save(self):
    #     """Save method for MemberTemporary."""
    #     pass

    # def get_absolute_url(self):
    #     """Return absolute url for MemberTemporary."""
    #     return ('')

    # TODO: Define custom methods here


class TransactionTemporary(models.Model):
    """Model definition for TransactionTemporary."""

    MemberDetails = models.ForeignKey('webui.MemberTemporary', on_delete=models.DO_NOTHING)
    inTime = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        """Meta definition for TransactionTemporary."""

        verbose_name = 'TransactionTemporary'
        verbose_name_plural = 'TransactionTemporarys'

    def __str__(self):
        """Unicode representation of TransactionTemporary."""
        return '{}'.format(self.inTime ) # TODO

    # def save(self):
    #     """Save method for TransactionTemporary."""
    #     pass

    # def get_absolute_url(self):
    #     """Return absolute url for TransactionTemporary."""
    #     return ('')

    # TODO: Define custom methods here

class MiscContact(models.Model):
    """Model definition for MiscContact."""

    name = models.CharField(max_length=500)
    role = models.CharField(max_length=500)
    contact = models.CharField(max_length=50)

    class Meta:
        """Meta definition for MiscContact."""

        verbose_name = 'MiscContact'
        verbose_name_plural = 'MiscContacts'

    def __str__(self):
        """Unicode representation of MiscContact."""
        return '{}'.format(self.name)

    # def save(self):
    #     """Save method for MiscContact."""
    #     pass

    # def get_absolute_url(self):
    #     """Return absolute url for MiscContact."""
    #     return ('')

    # TODO: Define custom methods here

attendance/webui/forms.py
from django import forms
from django.contrib.admin import widgets                                       
from .models import Transaction, Member ,MemberType, Center, GENDER_TYPE, SecurityPost
from django.core.exceptions import ValidationError
import re

GEEKS_CHOICES = Member.objects.values_list('id','id')

def validate_alt_contact(value):
    return re.search(r'd{10}$', value)


# class DateInput(forms.DateInput):
#     input_type = 'date'


# class TransactionForm(forms.ModelForm):
#     class Meta:
#         model = Transaction
#         # fields = '__all__'
#         exclude = ['status', 'misc']
#         widgets = {
#             'inTime': DateInput(),
#         }


    # def __init__(self, *args, **kwargs):
    #     super(TransactionForm, self).__init__(*args, **kwargs)
    #     # self.fields['username'].widget.attrs.update({'class' : 'ui input','placeholder':'Enter Username'})
    #     # self.fields['email'].widget.attrs.update({'class' : 'ui input','placeholder':'Enter email'})
    #     # self.fields['keywords'].widget.attrs.update({'class' : 'ui input','placeholder':'Enter Key words'})
    #     # self.fields['search_frequency'].widget.attrs.update({'class' : 'ui input','placeholder':'In Hours'})
    #     self.fields['inTime'].widget.attrs.update({'class' : 'ui calender'})
    #     self.fields['outtime'].widget.attrs.update({'type' : 'datetime-local'})


class TransactionForm(forms.Form):
    ID = forms.ChoiceField(
        choices = GEEKS_CHOICES,
        # queryset = Member.objects.all().values('id'),
        label = 'Select or Search #',
        widget=forms.Select(attrs={"_style": "search", "_dropdown_icon": "dropdown"})
    )

    name = forms.CharField(
        widget=forms.TextInput(attrs={
                                        "Placeholder": "Name", 
                                        "class": "ui " })
    )

    # MemberType = forms.ModelChoiceField(
    #     queryset=MemberType.objects.all(),
    #     widget=forms.Select(attrs={"_style": "search", "_dropdown_icon": "dropdown"})
    #     )

    # CenterDetails = forms.ModelChoiceField(
    #     queryset=Center.objects.all(),
    #     widget=forms.Select(attrs={"_style": "search", "_dropdown_icon": "dropdown"})
    # )

    FatherName = forms.CharField(
        widget=forms.TextInput(attrs={
                                        "Placeholder": "Father Name", 
                                        "class": "ui " })
    )

    # Gender = forms.ChoiceField(
    #     choices=GENDER_TYPE,
    #     widget=forms.Select(attrs={"_dropdown_icon": "dropdown"})
    # )

    Contact = forms.CharField(
        max_length=15,
        widget=forms.TextInput(attrs={
                                        "Placeholder": "Contact Number", 
                                        "class": "ui " }),
        required=False
    )

    AlternateContact = forms.CharField(
        max_length=15,
        required=False,
        widget=forms.TextInput(attrs={
                                        "Placeholder": "Alternate Contact Number", 
                                        "class": "ui " }),
        validators=[validate_alt_contact],
        help_text = "Enter 10 Digits"
    )

    Department = forms.CharField(
        max_length=50,
        widget=forms.TextInput(attrs={
                                        "Placeholder": "Department", 
                                        "class": "ui " })
    )

    SecurityPost = forms.ModelChoiceField(
        queryset=SecurityPost.objects.all(),
        widget=forms.Select(attrs={"_style": "search", "_dropdown_icon": "dropdown"})
        )
    

    # inTime = forms.DateTimeField(input_formats=['%Y-%m-%d %I:%M'], widget=forms.DateInput(attrs={'type':'datetime-local'}))
    # outTime = forms.DateTimeField(input_formats=['%Y-%m-%d %I:%M'], required=False, widget=forms.DateInput(attrs={'type':'datetime-local'}))

    inTime = forms.DateTimeField(input_formats=['%I:%M %p %d-%b-%Y'],
             widget = forms.DateTimeInput(
                 attrs={'type': 'datetime-local'},
                 format='%I:%M %p %d-%b-%Y')) 


    outime = forms.DateTimeField(input_formats=['%I:%M %p %d-%b-%Y'],
             widget = forms.DateTimeInput(
                 attrs={'type': 'datetime-local'},
                 format='%I:%M %p %d-%b-%Y')) 

attendance/webui/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView, ListView, FormView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from datetime import datetime, timedelta, date

# Models
from .models import SecurityPost, Member, Transaction

# Forms
from .forms import TransactionForm

# Create your views here.

class LandingPage(TemplateView):
    template_name = "webui/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        gates = SecurityPost.objects.all()
        
        results = {}
        datetoday = datetime.now() + timedelta(hours=5,minutes = 30)
        for gate in gates:
            results[gate.name] = Transaction.objects.filter(SecurityPostDetails=gate).filter(inTime__date = datetoday.date())

        context["results"] = results
        context["form"] = TransactionForm
        # import pdb; pdb.set_trace()
        return context

def index(request):
    return render(request,'webui/menu.html')

class MemberListView(ListView):
    model = Member

class CreateTransaction(FormView):
    template_name = "webui/transaction_form.html"
    form_class = TransactionForm
    success_url = reverse_lazy('webui:home')

    def form_invalid(self, form):
        date_format = '%Y-%m-%d %H:%M'
        outTime = datetime.strptime(form.data.get('outime').replace('T',' '), date_format)
        inTime = datetime.strptime(form.data.get('inTime').replace('T',' '), date_format)
        MemberDetails__id = form.data.get('ID')
        SecurityPostDetails__id = form.data.get('SecurityPost')
        inTime = inTime
        outtime = outTime
        obj = Transaction.objects.create(
            MemberDetails = Member.objects.get(pk=MemberDetails__id),
            SecurityPostDetails = SecurityPost.objects.get(pk=SecurityPostDetails__id),
            inTime = inTime,
            outtime = outtime
        )
        return HttpResponseRedirect(self.get_success_url())
        # return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

attendance/webui/templates/webui/dashboard.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block additional_head %}
  <meta http-equiv="refresh" content="900">
{% endblock additional_head %}

{% block content %}

<div class="card sticky-top"> <button data-toggle="modal" data-target="#exampleModalCenter" gate-id="{{gate.id}}" type="button" class="btn btn-primary btn-sm btn-block">Add More</button></div>

<div class="row">
{% for gate,transactions in results.items %}
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h3 style="font-weight:bold" class="card-title">{{ gate|upper }}</h3>
          <p class="card-text">
            <table class="table table-sm">
              <thead>
                <tr>
                  <th scope="col">Name</th>
                  <th scope="col">In Time</th>
                  <th scope="col">Out Time</th>
                  <th scope="col">Contact</th>
                </tr>
              </thead>
              <tbody>
                {% for transaction in transactions %}
                <tr class="table-danger">
                  <td>{{ transaction.MemberDetails.name }}</td>
                  <td>{{ transaction.inTime | date:"G:i:s"  }}</td>
                  <td outTime="{{ transaction.outtime }}" >{{ transaction.outtime | date:"G:i:s"  }}</td>
                  <td>{{ transaction.MemberDetails.phone_number }} <br> {% if transaction.MemberDetails.phone_number_alt %} {{ transaction.MemberDetails.phone_number_alt }}  {% endif %}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </p>
          {% comment %} <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> {% endcomment %}
        </div>
      </div>
    </div>
{% endfor %}
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Add More Person</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="/create-transaction" method="post">{% csrf_token %}
          {% crispy form %}
          <button type="submit" class="btn btn-primary">Submit</button>
          <button class="btn btn-secondary" type="reset">Reset </button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block additional_js %}
<script>
  $(document).ready(function(){
  $('#myModal').on('shown.bs.modal', function () {
    $('#myInput').trigger('focus')
  });

  $('#id_ID').on('change', function() {
      console.log(this.value)
      $.ajax({
          type: "GET",
          url: "/api/v1/member/" + this.value,
          dataType: "json",
          success: function (result, status, xhr) {
              $('#id_MemberType').val(result.MemberTypeDetails).prop('readonly','true');
              $('#id_name').val(result.name).prop('readonly','true');
              $('#id_CenterDetails').val(result.CenterDetails).prop('readonly','true');
              $('#id_FatherName').val(result.father_name).prop('readonly','true');
              $('#id_Gender').val(result.gender).prop('readonly','true');
              $('#id_Contact').val(result.contact).prop('readonly','true');
              $('#id_AlternateContact').val(result.altcontact).prop('readonly','true');
              $('#id_Department').val(result.department).prop('readonly','true');
          },
          error: function (xhr, status, error) {
              alert("Result: " + status + " " + error + " " + xhr.status + " " + xhr.statusText)
          }
      });
  });

  $('form').on('submit',function(){
      var inTime = new Date($('#id_inTime').val())
      var outTime = new Date($('#id_outtime').val())
      $(this).append(inTime,outTime);
      return true;
  });
});



</script>
{% endblock additional_js %}

attendance/webui/templates/webui/memberlist_list.html
{% extends "base.html" %}

{% block body %}
<h1>Members List</h1>

<table class="ui very basic table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Center</th>
        <th>Contact</th>
      </tr>
    </thead>
    <tbody>
    {% for member in object_list %}
      <tr>
        <td>{{ member.id }}</td>
        <td>{{ member.name }}</td>
        <td>{{ member.CenterDetails }}</td>
        <td>{{ member.contact }}<br>{{ member.altcontact }}</td>
    </tr>
    {% empty %}
        <td>No members yet.</td>
    {% endfor %}
    </ul>
    </tbody>
  </table>



<ul>
{% endblock body %}

attendance/webui/templates/webui/transaction_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block additional_css %}
    {% comment %} <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet"> {% endcomment %}
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/css/bootstrap-select.min.css" />
{% endblock additional_css %}

{% block content %}
 <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Save</button>
  </form>
{% endblock content %}

{% block additional_js %}

<script>
$(document).ready(function(){
    $('#id_ID').on('change', function() {
        console.log(this.value)
        $.ajax({
            type: "GET",
            url: "/api/v1/member/" + this.value,
            dataType: "json",
            success: function (result, status, xhr) {
                console.log(result)
                $('#id_MemberType').val(result.MemberTypeDetails).prop('readonly','true');

                $('#id_name').val(result.name).prop('readonly','true');

                $('#id_CenterDetails').val(result.CenterDetails).prop('readonly','true');

                $('#id_FatherName').val(result.father_name).prop('readonly','true');

                $('#id_Gender').val(result.gender).prop('readonly','true');

                $('#id_Contact').val(result.contact).prop('readonly','true');

                $('#id_Department').val(result.department).prop('readonly','true');

            },
            error: function (xhr, status, error) {
                alert("Result: " + status + " " + error + " " + xhr.status + " " + xhr.statusText)
            }
        });
    });

    $('form').on('submit',function(){
        var inTime = new Date($('#id_inTime').val())
        var outTime = new Date($('#id_outtime').val())
        $(this).append(inTime,outTime);
        return true;
    });

});

</script>

{% endblock additional_js %}

attendance/webui/templates/webui/transactionpermanent_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<form class="ui form" method="post">{% csrf_token %}
    {% for field in form %}
        <div class="inline fields">
            <div class="field">
                <label>{{ field.name | title }}</label>
            </div>
            <div class="field">
                {{ field }}
            </div>
        </div>
    {% endfor %}
    <input class="ui primary button" type="submit" value="Save">
    <input class="ui secondary button" type="reset" value="Reset">

</form>
{% endblock content %}

{% block additional_js %}

<script>
    window.addEventListener("load", function(){
        $('select[name = "ID"]')
        .addClass('search')
        .dropdown()
        ;
    });

    $('select').on('change', function() {
        $.ajax({
            type: "GET",
            url: "/api/v1/member/" + this.value,
            dataType: "json",
            success: function (result, status, xhr) {
                console.log(result)
                {% comment %} Assign MemberType {% endcomment %}
                $('#id_MemberType').val(result.MemberTypeDetails).prop('disabled', 'disabled');

                {% comment %} Assign Name {% endcomment %}
                $('#id_name').val(result.name).prop('disabled', 'disabled');

                {% comment %} Assign Center {% endcomment %}
                $('#id_CenterDetails').val(result.CenterDetails).prop('disabled', 'disabled');

                {% comment %} Assign Father Name {% endcomment %}
                $('#id_FatherName').val(result.father_name).prop('disabled', 'disabled');

                {% comment %} Assign Gender {% endcomment %}
                $('#id_Gender').val(result.gender).prop('disabled', 'disabled');

                {% comment %} Assign Contact {% endcomment %}
                $('#id_Contact').val(result.contact).prop('disabled', 'disabled');

                {% comment %} Assign Alternate Contact {% endcomment %}
                $('#id_AlternateContact').val(result.altcontact).prop('disabled', 'disabled');

                {% comment %} Assign Department {% endcomment %}
                $('#id_Department').val(result.department).prop('disabled', 'disabled');

            },
            error: function (xhr, status, error) {
                alert("Result: " + status + " " + error + " " + xhr.status + " " + xhr.statusText)
            }
        });
    });
</script>

{% endblock additional_js %}